### ISSUE TITLE
Supports Gulp 4

### ISSUE THREAD

**Issue by sylvainpolletvillard** [micha149/gulp-maven-deploy#19] opened 2018-02-21 12:51 UTC
Hi, 
I know it's an old project and you probably moved to something else. Anyway, it's worth asking: could you update this project to support Gulp 4 ? We have been waiting for Gulp 4 for years, and now that it is finally here, this is the last plugin in my toolchain that needs to be updated. I would be glad to help but I am afraid my knowledge of gulp internals is quite limited :worried:

**Comment by micha149** [comment] 2018-02-21 13:21
You are right. I personally don't use this module any more, because I am currently not deploying to a maven repository. I also didn't use gulp for a long time, so what is changed that this module will not work anymore?

Can you send a Pull Request with the necessary changes?

**Comment by sylvainpolletvillard** [comment] 2018-02-21 14:02
I wish I could do that but it's hard to find documentation about how to upgrade plugins, and gulp 4 development has taken way too long. Hopefully someone with the required knowledge and motivation will come one day. Anyway, thanks for your response, have a nice day

**Comment by micha149** [comment] 2018-02-21 14:15
What error do you get?

**Comment by sylvainpolletvillard** [comment] 2018-02-21 19:30
`Unhandled promise rejection (rejection id: 1): TypeError: file.pipe is not a function`

I try to look at other gulp plugins repos to see how they upgraded

**Comment by micha149** [comment] 2018-02-22 12:49
OK, I got it. The problem is, that on [gulpjs/vinyl](https://github.com/gulpjs/vinyl) the `pipe` method was removed.

**Comment by micha149** [comment] 2018-04-05 11:09
Should be fixed with [v1.0.2](https://github.com/micha149/gulp-maven-deploy/releases/tag/v1.0.2)

**Closed by micha149** 2018-04-05 11:09 UTC
